services:
  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - google-chrome:/home/node/.config/google-chrome-for-testing
    environment:
      CONTAINER: 1
      DISPLAY: ${DISPLAY:-novnc:0.0}
    healthcheck:
      disable: true
    cap_add:
      - SYS_ADMIN
    shm_size: 2gb

  novnc:
    image: theasp/novnc@sha256:1371f18087ee68af4730c2a106c06e60d8550c30f4a830cef44a8e524568cabb
    profiles:
      - novnc
    environment:
      DISPLAY_WIDTH: '${NOVNC_DISPLAY_WIDTH:-1600}'
      DISPLAY_HEIGHT: '${NOVNC_DISPLAY_HEIGHT:-968}'
    ports:
      - ${NOVNC_HOST:-127.0.0.1}:${NOVNC_PORT:-8080}:8080

volumes:
  google-chrome: {}
