name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Semver-style tag for release (e.g., v1.0.0)
        required: true

jobs:
  create-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check tag format
        run: |
          if [[ ! "${{ inputs.tag }}" =~ ^v ]]; then
            echo "Tag must start with 'v'"
            exit 1
          fi

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: package.json
          cache: yarn

      # https://github.com/killercup/cargo-edit/issues/864
      - name: Set version
        run: |
          tag="${{ inputs.tag }}"
          tag_no_v="${tag#v}"
          yarn version --new-version "$tag_no_v" --no-git-tag-version

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        id: generate-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          sign-commits: true
          title: Release ${{ inputs.tag }}
          branch: release/${{ inputs.tag }}
          delete-branch: true
